# GoReleaser configuration for Terraform Provider
# Reference: https://goreleaser.com/customization/terraform/

version: 2

# Project name and version
project_name: terraform-provider-keep

# Build configuration
builds:
  - id: "provider"
    main: ./main.go
    binary: terraform-provider-keep
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0

# Archive configuration
archives:
  - id: "provider"
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

# Checksums configuration for Terraform Registry
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
  # Disable signature for now - you'll need to set up GPG later
  # signature: "{{ .ArtifactName }}.sig"
  # Extra files to add to checksum
  extra_files:
    - glob: "*.zip"

# Release configuration
release:
  github:
    owner: ChrisGute
    name: terraform-provider-keep
  name_template: 'v{{.Version}}'
  draft: false
  prerelease: false
  # Don't delete the dist folder after release
  # so we can inspect the artifacts
  rm_dist: false

# Before hooks
before:
  hooks:
    - go mod download
    - go test -v -short ./...

# After hooks
after:
  hooks:
    - make gen-docs  # If you have documentation generation

# Terraform provider configuration
# This tells GoReleaser to generate the required files for the Terraform Registry
tf_legacy:
  enabled: true
  # This will create the required .terraformrc file
  files:
    - README.md
    - LICENSE
  # This will create the required .terraformrc file for the provider
  # You'll need to replace this with your actual namespace
  # and the correct registry URL if you're not using the public registry
  # registry: "registry.terraform.io"
  # namespace: "your-namespace"
