# GoReleaser configuration for Terraform Provider
# Based on the AWS provider's configuration
version: 2

# Project name and version
project_name: terraform-provider-keep

# Build configuration
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64  # Add ARM64 support for M1/M2 Macs
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    main: ./main.go
    binary: '{{ .ProjectName }}_v{{ .Version }}_x5'  # Required for Terraform CLI 0.12+
    mod_timestamp: '{{ .CommitTimestamp }}'

# Archive configuration
archives:
  - id: "default"
    files:
      # Include only the binary and license file
      - src: LICENSE
        dst: LICENSE.txt
      - src: README.md
    formats: ['zip']
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

# Checksums configuration for Terraform Registry
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  # Include extra files in checksum
  extra_files:
    - glob: '*.json'

# Release configuration
release:
  github:
    owner: ChrisGute
    name: terraform-provider-keep
  name_template: 'v{{.Version}}'
  prerelease: false

# Before hooks
before:
  hooks:
    - go mod download
    - go test -v -short ./...

# Signing configuration for Terraform Registry
signs:
  - cmd: gpg
    signature: ${artifact}.sig
    args: ["--batch", "--yes", "--detach-sign", "--armor", "--local-user", "3A2149B196C6519D17ED0DF90EF0E903DD42A003", "--output", "${signature}", "${artifact}"]
    artifacts: checksum
    # Environment variables that will be passed to the signing command
    env:
      - GPG_TTY=
      - GNUPGHOME=${HOME}/.gnupg
      - GPG_FINGERPRINT=3A2149B196C6519D17ED0DF90EF0E903DD42A003

# Snapshot configuration
snapshot:
  name_template: "{{ .Tag }}-next"
