# GoReleaser configuration for Terraform Provider
# Based on the AWS provider's configuration
version: 2

# Project name and version
project_name: terraform-provider-keep

# Build configuration
builds:
  - id: "default"
    main: ./main.go
    binary: '{{ .ProjectName }}_v{{ .Version }}_x5'  # Required for Terraform CLI 0.12+
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'

# Archive configuration
archives:
  - id: "default"
    files:
      # Include only the binary and license file
      - src: LICENSE
        dst: LICENSE.txt
      - src: README.md
    formats: ['zip']
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

# Checksums configuration for Terraform Registry
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  # Include extra files in checksum
  extra_files:
    - glob: '*.json'

# Release configuration
release:
  github:
    owner: ChrisGute
    name: terraform-provider-keep
  name_template: 'v{{.Version}}'
  prerelease: false

# Before hooks
before:
  hooks:
    - go mod download
    - go test -v -short ./...

# Signing configuration (disabled for now to simplify local testing)
# signs:
#   - args: ["sign", "--dearmor", "--file", "${artifact}", "--out", "${signature}"]
#     artifacts: checksum
#     cmd: gpg  # or 'signore' if using HashiCorp's signing service
#     signature: ${artifact}.sig

# Snapshot configuration
snapshot:
  name_template: "{{ .Tag }}-next"
