# Minimal GoReleaser config for early development
# Remove or simplify this file if not using GoReleaser yet

version: 2

# Project name and version
project_name: terraform-provider-keep

# Simple build configuration for local development
builds:
  - id: "local"
    main: ./main.go
    binary: terraform-provider-keep
    goos: ["linux", "darwin"]  # Only build for common dev platforms
    goarch: ["amd64"]          # Only build for amd64
    flags: ["-trimpath"]
    ldflags:
      - -s -w -X main.version={{.Version}}

dist: dist

# Skip checksums and signing for now
checksum:
  disable: true

# Minimal release configuration
release:
  github:
    owner: ChrisGute
    name: terraform-provider-keep
  name_template: 'v{{.Version}}'
  draft: true  # Create as draft by default

# Run basic tests before release
before:
  hooks:
    - go mod download
    - go test -v -short ./...
