# GoReleaser configuration for Terraform Provider
# Follows the official Terraform provider release format

# Project name and version
project_name: terraform-provider-keep

# Build configuration
builds:
  - id: "provider"
    main: ./main.go
    binary: terraform-provider-keep_v{{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0

# Archive configuration
archives:
  - id: "provider"
    name_template: >-
      {{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format: zip
    files:
      - README.md
      - LICENSE

# Checksums configuration for Terraform Registry
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
  # Disable signature for now as it's optional for Terraform Registry
  disable_sign: true

# Release configuration
release:
  github:
    owner: ChrisGute
    name: terraform-provider-keep
  name_template: 'v{{.Version}}'
  draft: false
  prerelease: false
  # Don't delete the dist folder
  rm_dist: false

# Before hooks
before:
  hooks:
    - go mod download
    - go test -v -short ./...

# Terraform provider configuration
# This tells GoReleaser to generate the required files for the Terraform Registry
tf_legacy:
  enabled: true
  # This will create the required .terraformrc file
  files:
    - README.md
    - LICENSE
