# Minimal GoReleaser config for Terraform Provider
# Compatible with older GoReleaser versions

# Project name and version
project_name: terraform-provider-keep

# Build configuration
builds:
  - id: "default"
    main: ./main.go
    binary: terraform-provider-keep
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0

# Archive configuration
archives:
  - id: "default"
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - README.md
      - LICENSE

# Checksums configuration for Terraform Registry
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

# Release configuration
release:
  github:
    owner: ChrisGute
    name: terraform-provider-keep
  name_template: 'v{{.Version}}'
  draft: false
  prerelease: false

# Before hooks
before:
  hooks:
    - go mod download
    - go test -v -short ./...
