name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build for all platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set env vars
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV

      - name: Build binary
        run: |
          mkdir -p dist
          go build -o dist/terraform-provider-keep_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }} ./

      - name: Create ZIP archive
        run: |
          cd dist
          zip terraform-provider-keep_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip terraform-provider-keep_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}

      # Remove per-binary checksum generation. We'll generate a single SHA256SUMS file after all builds.

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import

      # Remove per-binary signature generation. We'll sign the single SHA256SUMS file after all builds.

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-keep_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}
          path: |
            dist/terraform-provider-keep_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip
            dist/terraform-provider-keep_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip.sha256
            dist/terraform-provider-keep_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip.sha256.asc

  # New job to generate SHA256SUMS and sign it after all builds
  post-build:
    name: Aggregate Checksums and Sign
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Move all zip files to dist root
        run: |
          find dist -name "*.zip" -exec mv {} dist/ \;

      - name: Generate SHA256SUMS
        run: |
          cd dist
          sha256sum terraform-provider-keep_*.zip > terraform-provider-keep_${{ github.ref_name }}_SHA256SUMS

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import

      - name: Sign SHA256SUMS (binary signature)
        run: |
          cd dist
          gpg --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --output terraform-provider-keep_${{ github.ref_name }}_SHA256SUMS.sig --detach-sign terraform-provider-keep_${{ github.ref_name }}_SHA256SUMS

      - name: Upload SHA256SUMS and signature
        uses: actions/upload-artifact@v4
        with:
          name: sha256sums
          path: |
            dist/terraform-provider-keep_${{ github.ref_name }}_SHA256SUMS
            dist/terraform-provider-keep_${{ github.ref_name }}_SHA256SUMS.sig

  release:
    name: Create GitHub Release
    needs: post-build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Move SHA256SUMS and sig to dist root
        run: |
          find dist -name "terraform-provider-keep*_SHA256SUMS*" -exec mv {} dist/ \;

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.zip
            dist/terraform-provider-keep_${{ github.ref_name }}_SHA256SUMS
            dist/terraform-provider-keep_${{ github.ref_name }}_SHA256SUMS.sig
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            See CHANGELOG.md for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
